

services:
  mongodb:
    image: mongo:latest
    container_name: spill-mongodb
    ports:
      - "27017:27017"
    volumes:
        - mongo-data:/data/db
    restart: unless-stopped
  
  redis:
    image: redis:latest
    container_name: spill-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    
volumes:
  mongo-data: