services:
  web:
    container_name: "chat-web"
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      # - db
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - app_network
    restart: always
    volumes:
      - .:/code/app

  rabbitmq:
    container_name: "chat-rabbitmq"
    image: "rabbitmq:3.12-management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
    networks:
      - app_network
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s      # how often to run check
      timeout: 5s        # time allowed for the check
      retries: 5         # how many failures before unhealthy
      start_period: 10s  # grace period before starting checks

  # db:
  #   container_name: "chat-mongo"
  #   image: "mongo:6.0"
  #   ports:
  #     - "27017:27017"

networks:
  app_network:
    driver: bridge
  
